version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: woo_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
    - "3306:3306"

  redis:
    image: redis:7-alpine
    container_name: woo_redis
    restart: always
    ports:
      - "6379:6379"

  wordpress:
    image: wordpress:latest
    container_name: woo_app
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./wp-content:/var/www/html/wp-content

volumes:
  db_data: